version: 2

project_name: osquery-extension

before:
  hooks:
    - go mod tidy

builds:
  - id: osquery-extension
    main: ./
    binary: osquery-extension.ext
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE.txt
      - README.md
      - src: tables/fleetdm/LICENSE
        dst: licenses
        strip_parent: true
      - src: tables/fleetdm/ATTRIBUTION.md
        dst: licenses
        strip_parent: true

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"

release:
  draft: false
  prerelease: auto
